/**
 * AI-agent command generators (v0.53, tasks 4.9/4.10).
 *
 * `orion update` writes run-command files so an agent (Claude Code, Cursor)
 * drives Orion through its honest workflow — and, crucially, trusts the
 * Honest Receipt (via `orion badge <change>`) over its own feeling of "done".
 * Unique angle vs OpenSpec: the agent VERIFIES the result through the
 * certificate, it doesn't just follow a process.
 *
 * Idempotent: re-running writes the same content, never duplicates.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

const MARK =
  "<!-- @generated by orion update — do not edit; run `orion update` to refresh -->";

/** Claude Code slash-command: teaches use + honest-done gate. */
function claudeCommand(): string {
  return `${MARK}

# Orion workflow

Drive deterministic changes with the honest pipeline.

\`\`\`
orion new "<idea>"     # think → proposal
orion change <id>      # per-change ops (draft/forge/shield/out)
orion out <id>         # writes result.md + receipt.json (+ Honest Receipt)
\`\`\`

## Done gate (the rule)

A task is DONE **only when** the Honest Receipt proves it:

\`\`\`
orion badge <change>   # status=verified / partial / failing / not verified
\`\`\`

Check \`changes/<id>/receipt.json\` — it is the single source of truth.
- \`status\` missing or \`not verified\` → the task is NOT done.
- \`failing\` → fix and re-run the gate.
- Trust the receipt, not your feeling that it "looks complete".
`;
}

/** Cursor rule file (.mdc frontmatter) — same honest gate adapted to Cursor. */
function cursorRule(): string {
  return `---
description: Orion honest workflow + done gate (verify via Honest Receipt)
globs: changes/**/*, .orion/**
---
${MARK}

When working with Orion, run deterministic changes through the honest
pipeline: \`orion new\` → \`orion change <id>\` (draft/forge/shield) → \`orion out <id>\`.

**Done gate:** a task is complete ONLY when \`orion badge <change>\` shows
\`status=verified\` (or the receipt.json says so). Do not mark a task done by
your own judgment — verify through the Honest Receipt first.
`;
}

export interface UpdateResult {
  claude: boolean | null;
  cursor: boolean | null;
  files: string[];
  /** Files whose content changed this run (were rewritten). */
  refreshed: string[];
}

const CONTENT: Record<
  ".claude/commands/orion.md" | ".cursor/rules/orion.mdc",
  () => string
> = {
  ".claude/commands/orion.md": claudeCommand,
  ".cursor/rules/orion.mdc": cursorRule,
};

/**
 * Detect which agent dirs actually exist; write only those command files.
 * Idempotent: if an existing file already matches, it is left untouched
 * (not duplicated); a differing file is refreshed (regenerated).
 */
export function updateAgentFiles(root = process.cwd()): UpdateResult {
  const out: UpdateResult = {
    claude: false,
    cursor: false,
    files: [],
    refreshed: [],
  };
  const claudeDir = join(root, ".claude", "commands");
  if (existsSync(claudeDir)) out.claude = true;
  const cursorDir = join(root, ".cursor", "rules");
  if (existsSync(cursorDir)) out.cursor = true;

  for (const rel of Object.keys(CONTENT) as (keyof typeof CONTENT)[]) {
    out.files.push(rel);
  }

  const claudeEnabled = out.claude === true;
  if (claudeEnabled) {
    const path = join(root, ".claude", "commands", "orion.md");
    writeIfChanged(path, CONTENT[".claude/commands/orion.md"], out);
  }
  const cursorEnabled = out.cursor === true;
  if (cursorEnabled) {
    const path = join(root, ".cursor", "rules", "orion.mdc");
    writeIfChanged(path, CONTENT[".cursor/rules/orion.mdc"], out);
  }
  out.files = out.files.filter(
    (f) =>
      (f === ".claude/commands/orion.md" && claudeEnabled) ||
      (f === ".cursor/rules/orion.mdc" && cursorEnabled),
  );
  return out;
}

function writeIfChanged(
  path: string,
  gen: () => string,
  out: UpdateResult,
): void {
  const content = gen();
  const existing = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (existing !== content) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf8");
    out.refreshed.push(path);
  }
}
