/** Central type definitions for Orion. */

/** High-level skill names recognized by the CLI. */
export type SkillName = "think" | "draft" | "forge" | "shield" | "out";

/** Commands registered in the CLI dispatcher. */
export type CommandName =
  SkillName | "track" | "scale" | "tdd" | "metrics" | "help";

/** Cache keys are strings, namespaced with a colon prefix, e.g. `scale:yagni:<hash>`. */
export type CacheKey = string;

/** Lifecycle status of a TDD task. */
export type TaskStatus = "RED" | "GREEN" | "REFACTOR" | "DONE";

/** YAGNI ladder stage names. */
export type ScaleStageName =
  "yagni" | "reuse" | "stdlib" | "native" | "dep" | "oneLiner" | "minimum";

/** Configuration for the OrionTrack cache (read from `src/config/orionTrack.json`). */
export interface TrackConfig {
  maxSize: number;
  ttlDays: number;
}

/** Configuration for the scale ladder (read from `src/config/orionScale.json`). */
export interface ScaleConfig {
  stages: ScaleStageName[];
}

/** One stage of the YAGNI ladder. */
export interface ScaleStage {
  name: ScaleStageName;
  handler: (code: string) => Promise<string> | string;
}

/** Configuration for the TDD engine (read from `src/config/orionTdd.json`). */
export interface TddConfig {
  testTemplate: string;
  testDir: string;
  srcDir: string;
  command: string;
  minCoverage: number;
}

/** A user proposal gathered by the `think` skill. */
export interface Proposal {
  title: string;
  goal: string;
  platform: string;
  constraints: string;
  budget: string;
  /** Clarity of the original prompt: "clear" once refined, "vague" if left as-is. */
  clarity?: "clear" | "vague";
  /** Prompt language used for clarifying questions. */
  language?: "en" | "ru";
  /** Past self-correction lessons this idea relates to (v0.12). */
  appliesLessons?: string[];
}

/** Set of artifacts generated by the `draft` skill. */
export interface ArtifactSet {
  proposal: string;
  specs: string[];
  design: string;
  tasks: string;
  /** Snippets directory created for `forge` (v0.8). */
  snippets?: string;
  /** Existing files left untouched (idempotent re-draft). */
  skipped?: string[];
}

/** Result of one guard-rail check in `shield`. */
export interface GuardCheckResult {
  step:
    | "lint"
    | "type"
    | "test"
    | "drift"
    | "yagni"
    | "economy"
    | "security"
    | "verifiability";
  status: "PASS" | "FAIL" | "SKIP" | "WARN";
  detail?: string;
  /**
   * True when this check cannot fully support a strong verdict (e.g. the
   * test step passed but the repo has no meaningful assertions). Honesty,
   * never a gate.
   */
  weak?: boolean;
}

/** Full report produced by the `shield` skill. */
export interface GuardReport {
  changeId: string;
  checks: GuardCheckResult[];
  allPass: boolean;
  generatedAt: string;
  /**
   * Hash of the project source + the change at shield time (v0.10).
   * `out` and `next` compare it with the current hash to detect a stale
   * guard verdict — never present yesterday's PASS as today's truth.
   */
  contextHash?: string;
}

/** Statistics exposed by OrionTrack.getStats(). */
export interface TrackStats {
  count: number;
  size: number;
  lastPrune: string | null;
  /** On-disk cache schema version (v0.19): diagnostic for track status. */
  schemaVersion: number;
}
